### ISSUE TITLE
question about options filter for "-e"

### ISSUE THREAD

**Issue by NanFeng009** [dkogan/ltrace#12]
based on code comment, only the filter starts with '-' there will be an implicitly rule *@*. but from code both '+' and '-" will have an implicitly rule '*@*, am right?
is comment wrong or code wrong? for me i think this implicitly rule don't make sense.  '-' or '+' can just decorate firstly rule. for example
"-malloc@libc.so' means exclude malloc on libc.so while "+malloc@libc.so" means include malloc on libc.so.   why need this impilictly rule?
parse_filter(struct filter *filt, char *expr, int operators)
{
	/* Filter is a chain of sym@lib rules separated by '-' or '+'.
	 * If the filter expression starts with '-', the missing
	 * initial rule is implicitly *@*.  */
	 *...
		} else if (expr[s] == '-' || expr[s] == '+') {
			type = expr[s] == '-' ? FR_SUBTRACT : FR_ADD;
			expr[s] = 0;
			libname = "*";
			expr = next;

**Comment by dkogan** [comment]
This is just a fork. I don't maintain this project. I don't think anybody does.
